#!/bin/bash

echo 'УСТАНОВКА БАЗОВОЙ СИСТЕМЫ'

#clear &&
pacstrap /mnt linux-firmware linux-zen-headers linux-zen base base-devel nano dhcpcd dialog wpa_supplicant netctl mc git wget &&   
genfstab -U /mnt >> /mnt/etc/fstab


echo 'ПЕРЕХОД В НОВОЕ ОКРУЖЕНИЕ'

arch-chroot /mnt /bin/bash &&
echo "MODULES=($MODULE)" > /etc/mkinitcpio.conf &&
echo "BINARIES=()" >> /etc/mkinitcpio.conf &&
echo "FILES=()" >> /etc/mkinitcpio.conf &&
echo "HOOKS=(base udev autodetect modconf block keymap filesystems keyboard fsck)" >> /etc/mkinitcpio.conf &&
